/// Learned mean price by hour with the computed ToU reference (0.45 in 07:00–19:00 else 0.15, spec §4).
table FactPriceByHour
	lineageTag: ba22b998-8a9d-4b3e-9b76-561eab56c720

	column hour
		dataType: int64
		isHidden
		lineageTag: 0f044294-aba7-49ab-b509-ed2ad221d171
		summarizeBy: none
		sourceColumn: hour

	column ppo_mean_price
		dataType: double
		formatString: £0.000
		lineageTag: f9441fe7-a016-4714-aec0-05129502bcfa
		summarizeBy: none
		sourceColumn: ppo_mean_price

	column tou_reference_price
		dataType: double
		formatString: £0.000
		lineageTag: 523bf0c0-e0cf-4eb8-a58c-7e83ee520ecb
		summarizeBy: none
		sourceColumn: tou_reference_price

	partition FactPriceByHour = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(ResultsFolder & "ppo_price_by_hour.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  Typed = Table.TransformColumnTypes(Promoted, {{"hour", Int64.Type}, {"price", type number}}),
				  Renamed = Table.RenameColumns(Typed, {{"price", "ppo_mean_price"}}),
				  WithRef = Table.AddColumn(Renamed, "tou_reference_price", each if [hour] >= 7 and [hour] <= 18 then 0.45 else 0.15, type number)
				in
				  WithRef

