/// Calibration fact, grain: distribution (spec §4).
table FactCalibration
	lineageTag: 9470fda7-4a3f-48ee-8bf0-cccbd314cc91

	column distribution
		dataType: string
		isHidden
		lineageTag: 2899218d-bf68-4fcc-a744-a108bdbac53d
		summarizeBy: none
		sourceColumn: distribution

	column ks_statistic
		dataType: double
		formatString: 0.000
		lineageTag: 943bcb18-2126-4a10-ab25-5eba5c629c7f
		summarizeBy: none
		sourceColumn: ks_statistic

	column sim_mean
		dataType: double
		lineageTag: 773b8191-804d-40b9-bd1e-e648493fea6d
		summarizeBy: none
		sourceColumn: sim_mean

	column real_mean
		dataType: double
		lineageTag: 6407740d-a9a5-4be4-93e4-09288f9be916
		summarizeBy: none
		sourceColumn: real_mean

	partition FactCalibration = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(ResultsFolder & "calibration_summary.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  Typed = Table.TransformColumnTypes(Promoted, {{"distribution", type text}, {"ks_statistic", type number}, {"sim_mean", type number}, {"real_mean", type number}})
				in
				  Typed

